Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: true
    dense_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    global_average_pooling1d:
      Precision:
        result: fixed<16,6>
      Trace: true
    input_layer:
      Precision: ap_fixed<12,4,AP_RND,AP_SAT>
      Trace: true
    phi1:
      ConvImplementation: Pointwise
      ParallelizationFactor: 1
      Precision:
        bias: fixed<8,1>
        result: fixed<16,6>
        weight: fixed<8,1>
      ReuseFactor: 4
      Strategy: Latency
      Trace: true
    phi1_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    phi2:
      ConvImplementation: Pointwise
      ParallelizationFactor: 1
      Precision:
        bias: fixed<8,1>
        result: fixed<16,6>
        weight: fixed<8,1>
      ReuseFactor: 4
      Strategy: Latency
      Trace: true
    phi2_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    phi3:
      ConvImplementation: Pointwise
      ParallelizationFactor: 1
      Precision:
        bias: fixed<8,1>
        result: fixed<16,6>
        weight: fixed<8,1>
      ReuseFactor: 4
      Strategy: Latency
      Trace: true
    phi3_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    q_activation:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: true
    q_activation_1:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: true
    q_activation_2:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: true
    q_activation_3:
      Precision:
        result: fixed<12,4,RND_CONV,SAT>
      Trace: true
    q_activation_4:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: true
    rho:
      Precision:
        bias: fixed<8,1>
        result: fixed<16,6>
        weight: fixed<8,1>
      Trace: true
    rho_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    softmax:
      Precision:
        result: fixed<16,6>
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'trained_deepsets/deepsinv_synthable_8bits_16const_ptetaphi_kfolds/kfold_0/synthesis_test/keras_model.h5'
OutputDir: trained_deepsets/deepsinv_synthable_8bits_16const_ptetaphi_kfolds/kfold_0/synthesis_test
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: ebffBeBF
Version: 1.0.0
